# Generated by Django 3.1.3 on 2022-01-26 12:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedId', models.IntegerField(default=0)),
                ('nickname', models.CharField(default=False, max_length=200)),
                ('isMarked', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default=False, max_length=24)),
                ('subject', models.CharField(default=False, max_length=200)),
                ('content', models.TextField()),
                ('image', models.TextField(null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedId', models.IntegerField(default=0)),
                ('nickname', models.CharField(default=False, max_length=200)),
                ('isLike', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedId', models.IntegerField(default=0)),
                ('nickname', models.CharField(default=False, max_length=200)),
                ('replyFeed', models.TextField()),
            ],
        ),
    ]
